### ISSUE TITLE
App crashes on refresh

### ISSUE THREAD

**Issue by jimmyfo** [jimmyfo/MineMonitor#1]
Moto x4, dev mode enabled, 7.1.1, aeon-pool.com

User pastebin attached below. Appears to be chart related.

**Comment by jimmyfo** [comment]
Source: https://pastebin.com/5NcnxhQx


`01-07 21:53:58.251  3948  3948 V ACCESSIBILITY: CLICK - text: WAIT TO REFRESH (60)...; viewId: null
01-07 21:53:58.251  3948  3948 V JOAOMGCD: AutoInput-CLICK - text: WAIT TO REFRESH (60)...; viewId: null
01-07 21:53:58.262  3948  3948 V LASTMESSAGEk: Received last update com.joaomgcd.accessibility.a.b@2d537736
01-07 21:53:58.298  3948  1364 D EventBus: No subscribers registered for event class com.joaomgcd.log.m
01-07 21:53:58.298  3948  1364 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.g
01-07 21:53:58.326  3339 26061 I DeviceScanner: [MDNS] Received response from "Kitchen speaker" (08c304a0d8f59ed8eab3d1b4c4589349) with result "0 No change"
01-07 21:53:58.330  3339 26061 I DeviceScanner: [MDNS] Received response from "Kinderzimmer speaker 2" (0bccad6e5ce4adec1311a8ba3833f38d) with result "0 No change"
01-07 21:53:58.338  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.363  3339 26061 I DeviceScanner: [MDNS] Received response from "Wohnzimmer speaker" (8c7029cc155d55e8a80e6f04ba4bd0db) with result "0 No change"
01-07 21:53:58.366  3339 26061 I DeviceScanner: [MDNS] Received response from "Kinderzimmer speaker 2" (0bccad6e5ce4adec1311a8ba3833f38d) with result "0 No change"
01-07 21:53:58.369  3339 26061 I DeviceScanner: [MDNS] Received response from "Kitchen speaker" (08c304a0d8f59ed8eab3d1b4c4589349) with result "0 No change"
01-07 21:53:58.376  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.376  3172  6985 I Places  : ?: PlacesBleScanner stop()
01-07 21:53:58.377  3172  3172 I BeaconBle: Places requested to stop scan
01-07 21:53:58.378  3339 26061 I DeviceScanner: [MDNS] Received response from "Kitchen speaker" (08c304a0d8f59ed8eab3d1b4c4589349) with result "0 No change"
01-07 21:53:58.384  3172  3172 I BeaconBle: ZERO_POWER is disabled.
01-07 21:53:58.384  3339 26061 I DeviceScanner: [MDNS] Received response from "Kinderzimmer speaker 2" (0bccad6e5ce4adec1311a8ba3833f38d) with result "0 No change"
01-07 21:53:58.384  3172  3172 I BeaconBle: 'L' hardware scan: scan stopped, no powered clients
01-07 21:53:58.384  3172  3172 I BeaconBle: Scan canceled successfully.
01-07 21:53:58.389  3339 26061 I DeviceScanner: [MDNS] Received response from "Wohnzimmer speaker" (8c7029cc155d55e8a80e6f04ba4bd0db) with result "0 No change"
01-07 21:53:58.395  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.397  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.397  3172  6985 I PlaceInferenceEngine: [anon] Changed inference mode: 105
01-07 21:53:58.485  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.491  3339 26061 I DeviceScanner: [MDNS] Received response from "Kinderzimmer speaker 2" (0bccad6e5ce4adec1311a8ba3833f38d) with result "0 No change"
01-07 21:53:58.494  3339 26061 I DeviceScanner: [MDNS] Received response from "Wohnzimmer speaker" (8c7029cc155d55e8a80e6f04ba4bd0db) with result "0 No change"
01-07 21:53:58.499  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.502  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.509  3339 26061 I DeviceScanner: [MDNS] Received response from "Kitchen speaker" (08c304a0d8f59ed8eab3d1b4c4589349) with result "0 No change"
01-07 21:53:58.523  3339 26061 I DeviceScanner: [MDNS] Received response from "Wohnzimmer speaker" (8c7029cc155d55e8a80e6f04ba4bd0db) with result "0 No change"
01-07 21:53:58.530  3339 26061 I DeviceScanner: [MDNS] Received response from "Wohnzimmer speaker" (8c7029cc155d55e8a80e6f04ba4bd0db) with result "0 No change"
01-07 21:53:58.530  1345  1350 I art     : Do partial code cache collection, code=26KB, data=30KB
01-07 21:53:58.530  1345  1350 I art     : After code cache collection, code=26KB, data=30KB
01-07 21:53:58.530  1345  1350 I art     : Increasing code cache capacity to 128KB
01-07 21:53:58.535  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.539  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.546  3339 26061 I DeviceScanner: [MDNS] Received response from "Kitchen speaker" (08c304a0d8f59ed8eab3d1b4c4589349) with result "0 No change"
01-07 21:53:58.548  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.553  3339 26061 I DeviceScanner: [MDNS] Received response from "Kinderzimmer speaker 2" (0bccad6e5ce4adec1311a8ba3833f38d) with result "0 No change"
01-07 21:53:58.560  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.566  3339 26061 I DeviceScanner: [MDNS] Received response from "Casty" (4dc54617cb9bb795e0b68debc2ca3dfd) with result "0 No change"
01-07 21:53:58.600  1345  1350 I art     : Do partial code cache collection, code=45KB, data=55KB
01-07 21:53:58.600  1345  1350 I art     : After code cache collection, code=45KB, data=55KB
01-07 21:53:58.600  1345  1350 I art     : Increasing code cache capacity to 256KB
01-07 21:53:58.704  1345  1350 I art     : Compiler allocated 5MB to compile void com.jimmyfo.cyrpto.minemonitor.MainActivity$9.onResponse(org.json.JSONObject)
01-07 21:53:58.735  1912  1940 I ActivityManager: Start proc 1401:com.google.android.apps.fitness/u0a236 for broadcast com.google.android.apps.fitness/.api.services.ActivityUpsamplingReceiver
01-07 21:53:58.760 29305  1455 D CE-GmsVehicleService: ARC: ActivityRecognitionResult [probableActivities=[DetectedActivity [type=STILL, confidence=29], DetectedActivity [type=UNKNOWN, confidence=22], DetectedActivity [type=IN_VEHICLE, confidence=14], DetectedActivity [type=ON_FOOT, confidence=12], DetectedActivity [type=WALKING, confidence=12], DetectedActivity [type=ON_BICYCLE, confidence=6], DetectedActivity [type=RUNNING, confidence=5]], timeMillis=1515358438708, elapsedRealtimeMillis=197521908]
01-07 21:53:58.760  1345  1350 I art     : Do full code cache collection, code=103KB, data=124KB
01-07 21:53:58.762  1345  1350 I art     : Waiting for a blocking GC JitCodeCache
01-07 21:53:58.767  1345  1345 D AndroidRuntime: Shutting down VM
01-07 21:53:58.767  1345  1345 W System.err: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
01-07 21:53:58.774  1345  1345 W System.err:    at java.util.ArrayList.get(ArrayList.java:411)
01-07 21:53:58.774  1345  1345 W System.err:    at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
01-07 21:53:58.774  1345  1345 W System.err:    at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
01-07 21:53:58.774  1345  1345 W System.err:    at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
01-07 21:53:58.774  1345  1345 W System.err:    at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:264)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.View.draw(View.java:17201)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.View.updateDisplayListIfDirty(View.java:16183)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.View.draw(View.java:16967)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.ViewGroup.drawChild(ViewGroup.java:3731)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3517)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.View.updateDisplayListIfDirty(View.java:16178)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.View.draw(View.java:16967)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.ViewGroup.drawChild(ViewGroup.java:3731)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3517)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.View.updateDisplayListIfDirty(View.java:16178)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.View.draw(View.java:16967)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.ViewGroup.drawChild(ViewGroup.java:3731)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3517)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.View.draw(View.java:17204)
01-07 21:53:58.774  1345  1345 W System.err:    at android.widget.ScrollView.draw(ScrollView.java:1725)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.View.updateDisplayListIfDirty(View.java:16183)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.View.draw(View.java:16967)
01-07 21:53:58.774  1345  1345 W System.err:    at android.view.ViewGroup.drawChild(ViewGroup.java:3731)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3517)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.View.updateDisplayListIfDirty(View.java:16178)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.View.draw(View.java:16967)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewGroup.drawChild(ViewGroup.java:3731)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3517)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.View.updateDisplayListIfDirty(View.java:16178)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.View.draw(View.java:16967)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewGroup.drawChild(ViewGroup.java:3731)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3517)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.View.updateDisplayListIfDirty(View.java:16178)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.View.draw(View.java:16967)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewGroup.drawChild(ViewGroup.java:3731)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3517)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.View.updateDisplayListIfDirty(View.java:16178)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.View.draw(View.java:16967)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewGroup.drawChild(ViewGroup.java:3731)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3517)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.View.draw(View.java:17204)
01-07 21:53:58.775  1345  1345 W System.err:    at com.android.internal.policy.DecorView.draw(DecorView.java:753)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.View.updateDisplayListIfDirty(View.java:16183)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2822)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2630)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2237)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1276)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6419)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:686)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.Choreographer.doFrame(Choreographer.java:621)
01-07 21:53:58.775  1345  1345 W System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
01-07 21:53:58.776  1345  1345 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
01-07 21:53:58.776  1345  1345 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
01-07 21:53:58.776  1345  1345 W System.err:    at android.os.Looper.loop(Looper.java:154)
01-07 21:53:58.776  1345  1345 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6165)
01-07 21:53:58.776  1345  1345 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
01-07 21:53:58.776  1345  1345 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
01-07 21:53:58.776  1345  1345 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
01-07 21:53:58.776  1345  1345 E MainActivity: [Ljava.lang.StackTraceElement;@8f2ae16
01-07 21:53:58.785  1345  1350 I art     : WaitForGcToComplete blocked for 23.297ms for cause JitCodeCache
01-07 21:53:58.785  1345  1350 I art     : Starting a blocking GC JitCodeCache
01-07 21:53:58.786  1345  1350 I art     : After code cache collection, code=88KB, data=100KB
01-07 21:53:58.795  1345  1356 I art     : Starting a blocking GC HeapTrim`

**Comment by jimmyfo** [comment]
Issue is apparently that the chart software allows empty sets to be assigned without error, but on render (after event fires) is when error occurs. Waiting on user confirmation of fix.

**Comment by jimmyfo** [comment]
Issue is apparently that the chart software allows empty sets to be assigned without error, but on render (after event fires) is when error occurs. Waiting on user confirmation of fix.
